CREATE SCHEMA userregistry;
CREATE ROLE backend LOGIN PASSWORD '123';
GRANT ALL ON SCHEMA userregistry TO backend;
ALTER DEFAULT PRIVILEGES IN SCHEMA userregistry GRANT ALL PRIVILEGES ON TABLES TO backend;
